README.md

- make sure the image has a name
- remove the container after launch

README: improve podman commands

---

components/common/Avatar/index.tsx
components/common/Button.tsx
components/phonebook/Filter.tsx
components/phonebook/index.ts
lib/phonebook.ts
package-lock.json
package.json
pages/_app.tsx
pages/phonebook.tsx
stories/Avatar.stories.tsx
stories/Button.stories.tsx
theme/Theme.ts

Phonebook UI

---

lib/phonebook.ts
package-lock.json
package.json
pages/_app.tsx
pages/phonebook.tsx

Show phonebook skeleton while waiting for API response.
Skeleton library provided by https://github.com/dvtng/react-loading-skeleton

Phonebook skeleton

---

.gitignore
pages/_app.tsx
pages/_document.tsx
public/config/config.development.js

- Fix app config loading script
- .gitignore: remove `config.development.js` and add `.vscode`

Fix app config & .gitignore

---

components/common/Avatar/index.tsx
components/common/Dropdown/DropdownItem.tsx
components/common/InlineNotification.tsx
components/common/Switch.tsx
components/common/TextInput.tsx
components/layout/MobileNavBar.tsx
components/layout/NavBar.tsx
components/layout/SideBar.tsx
components/layout/TopBar.tsx
components/layout/speed_dial/CreateOrEditSpeedDialDrawerContent.tsx
components/phonebook/CreateOrEditContactDrawerContent.tsx
components/phonebook/Filter.tsx
components/phonebook/ShowContactDrawerContent.tsx
config/routes.ts
package-lock.json
package.json
pages/login.tsx
pages/phonebook.tsx
stories/Button.stories.tsx
stories/Dropdown.stories.tsx
stories/EmptyState.stories.tsx
stories/InlineNotification.stories.tsx
stories/Modal.stories.tsx
stories/TextInput.stories.tsx
theme/Theme.ts
theme/Types.ts

Replace Material Design icons with Font Awesome
Other changes:
- Remove `react-icons` package
- Fix status badge
- Minor fixes

Use Font Awesome icons

---

Dockerfile
README.md
entrypoint.sh
public/config/config.production.js.sample

Added an entrypoint script that generates the configuration file using environment variables at container startup

Use environment variables for configuration

---

.github/workflows/build-image.yml
.github/workflows/clean-registry.yml
README.md

Add 2 actions:
- build image and publish to GitHub registry
- cleanup non-tagged images

CI integration

---

components/history/Filter.tsx
components/history/ShowContactHistory.tsx
components/history/index.ts
components/layout/SideDrawer.tsx
lib/history.ts
lib/utils.ts
package-lock.json
package.json
pages/history.tsx

- History page UI
- History detail drawer (ShowContactHistory.tsx)

Created history pages

---

components/history/Filter.tsx
components/history/ShowContactHistory.tsx
pages/history.tsx

- Fixed wrong dimension text input filter
- Fixed various inconsistent colors between dark theme and light theme
- Fixed skeleton in case of mobile device
- Fixed the alignment of the destination icon

History: fixed various UI bug

---

components/history/ShowContactHistory.tsx
components/settings/ClearCache.tsx
components/settings/index.ts
lib/settings.ts
lib/utils.ts
pages/history.tsx
pages/settings.tsx

- Fixed wrong last call list inside history drawer
- Created clear cache button inside the settings section

History: fixed wrong search for drawer

---

components/history/Filter.tsx
components/layout/TopBar.tsx
lib/topBar.ts

- Fixed wrong save in the history local storage
- Created missing button for the change of the user status
- Created modal to insert the number for the callforward
- Fixed the Ui for mobile devices

Created the change presence menu

---

components/layout/TopBar.tsx

- Fixed wrong title dimension inside presence menù
- Fixed wrong presence value inside avatar menù

Fixed missing Offline status inside history presence

---

components/history/AddToPhonebookDrawer.tsx
components/history/ShowHistoryDrawerContent.tsx
components/layout/SideDrawer.tsx
components/layout/TopBar.tsx
components/phonebook/CreateOrEditContactDrawerContent.tsx
lib/history.ts
lib/phonebook.ts
pages/history.tsx
pages/phonebook.tsx

- From History drawer is now possible to create new contacts 
- Added a new drawer with phonebook resume and filter inside on ```Add to phonebook``` button inside drawer history
- Changed icon for the ```Create contact``` button

History: added new drawer to save new numbers

---

components/history/AddToPhonebookDrawer.tsx
components/history/ShowHistoryDrawerContent.tsx
components/layout/SideDrawer.tsx
components/layout/speed_dial/CreateOrEditSpeedDialDrawerContent.tsx
components/operators/ShowOperatorDrawerContent.tsx
components/phonebook/ContactSummary.tsx
components/phonebook/CreateOrEditContactDrawerContent.tsx
components/phonebook/ShowContactDrawerContent.tsx

- Inserted title inside of every drawer

Added title inside drawers

---

components/common/SideDrawerCloseIcon.tsx
components/layout/Layout.tsx
components/layout/TopBar.tsx
models/user.ts

- Fixed missing status dot update on ```MainPresence``` status change
- Fixed missing border change presence menù 
- Fixed ```on click``` position from ```<span>``` to ```<button>```

Status dot fix and various UI enhancements

---

components/history/LastCallsDrawerTable.tsx
components/settings/ClearCache.tsx
pages/history.tsx

- Enhance style in `history.tsx` and `LastCallsDrawerTable.tsx`
- Clean up code

History & last calls drawer table: enhance style

---

components/history/Filter.tsx
components/layout/MobileNavBar.tsx
components/operators/Filter.tsx
components/phonebook/Filter.tsx

- Fixed closed icon for mobile version of drawer

Fixed close button for mobile device

---

components/common/IconSwitch.tsx
components/history/Filter.tsx
components/layout/NotificationsDrawerContent.tsx
components/operators/Filter.tsx
components/operators/OperatorSummary.tsx
components/operators/ShowOperatorDrawerContent.tsx
components/phonebook/Filter.tsx
public/locales/en/translation.json
public/locales/it/translation.json
stories/IconSwitch.stories.tsx

- New style for style icon when not active ( light instead of solid )
- Changed icon and name for the ```spy``` action
- Changed the space between search inputs and filters

Changed star icon not selected

---

public/locales/en/translation.json

Added missing Queues pages inside title

Added missing translation favicon title

---

pages/_app.tsx

Reverts nethesis/nethvoice-cti#98

Revert "Avoid phone-island styles overwriting"

---

components/layout/Layout.tsx
lib/operators.ts
package-lock.json
package.json
pages/operators.tsx

- Load more operators as the user scrolls down
- Use `react-infinite-scroll-component` npm package

Infinite scroll for operators list

---

components/history/LastCallsDrawerTable.tsx
components/layout/NavBar.tsx
components/layout/NotificationsDrawerContent.tsx
components/queues/QueuesManagementView.tsx
package-lock.json
package.json
pages/_app.tsx
public/locales/en/translation.json
styles/globals.css

Replace standard browser tooltips (using `title` attribute) with [`react-tooltip`](https://github.com/ReactTooltip/react-tooltip)

Use react-tooltip tooltips

---

components/queues/QueuesManagementView.tsx
models/queues.ts

Initially show a limited number of items in queue operators list

Queues: infinite scroll for queue operators

---

lib/operators.ts
lib/queuesLib.tsx
models/queues.ts
pages/operators.tsx
tailwind.config.js

Fix infinite scroll on very large screens (e.g. 4k resolution)

Operators: fix infinite scroll

---

components/history/Filter.tsx
components/history/ShowHistoryDrawerContent.tsx
components/operators/ShowOperatorDrawerContent.tsx
components/queues/QueuesManagementView.tsx
lib/history.ts
pages/history.tsx
pages/phonebook.tsx
pages/queues.tsx

Hide features that users with basic profile cannot access:
- Hide PBX calls history
- Hide queue calls and statistics
Other changes:
- Fix phonebook empty state
- History filter: fix the name of some variables

Bugfix for users with basic profile

---

components/history/ShowHistoryDrawerContent.tsx
components/layout/Layout.tsx
lib/history.ts
lib/utils.ts
models/ctiStatus.ts
pages/login.tsx
public/locales/en/translation.json
public/locales/it/translation.json

- Added force logout event in case of app already open in another page

Added force logout event

---

components/layout/SpeedDial.tsx
components/lines/RulesView.tsx
lib/speedDial.ts
lib/utils.ts
public/locales/en/translation.json
public/locales/it/translation.json
services/phonebook.ts

- New dropdown menu inside speed dial drawer
- Created missing translations
- Delete all function inside speed dial drawer
- Import speed dial from Csv function
- Export speed dial function

Create import export speed dial dropdown menu

---

components/layout/GlobalSearch.tsx
components/layout/TopBar.tsx
components/operators/OperatorSummary.tsx
public/locales/en/translation.json

- Missing phone action inside operator drawer

Various minor ui fix

---

components/history/CallsSource.tsx
components/history/LastCallsDrawerTable.tsx
components/history/UserCallStatusIcon.tsx
components/layout/UserLastCalls.tsx
components/layout/UserNavBar.tsx
components/queueManager/Monitor/Monitor.tsx

Get icon and status from store

Fixed last calls section avatar and presence dot

---

components/layout/Layout.tsx
components/layout/UserLastCalls.tsx
models/ctiStatus.ts
pages/login.tsx
public/locales/en/translation.json

Refresh user information ( /me) on: 
- Change tab
- After spending 60 minutes on the current page

Refresh user information

---

components/layout/Layout.tsx
components/layout/UserLastCalls.tsx
models/index.ts
models/lastCalls.ts

Solved multiple api calls of latest calls for nethvoice-cti user

Fixed double request for last calls

---

components/common/ActionCall.tsx
components/lines/AnnouncementView.tsx
lib/utils.ts

Merge after: https://github.com/nethesis/phone-island/pull/38

events. rename to match new phone-island events

---

entrypoint.sh

https://github.com/nethesis/ns8-nethvoice/pull/143

add timezone info to ui configuration file

---

components/history/CallsDate.tsx
lib/dateTime.ts
lib/utils.ts
package-lock.json
package.json

Reference: https://github.com/nethesis/ns8-nethvoice/issues/120

Fixed timezone with server and client localization

---

components/layout/Layout.tsx
components/layout/TopBar.tsx
components/layout/UserNavBar.tsx
components/settings/Integrations.tsx
models/user.ts
package-lock.json
package.json
pages/settings.tsx
public/locales/en/translation.json
public/locales/it/translation.json

Reference: https://github.com/nethesis/ns8-nethvoice/issues/125

Settings. Added app and integration permission control

---

entrypoint.sh

Read `TIMEZONE` env var from: https://github.com/nethesis/ns8-nethvoice/pull/176

entrypoint.sh. use TIMEZONE & VOICE_ENDPOINT envs

---

components/devices/SwitchInputOutputDrawerContent.tsx

https://github.com/NethServer/dev/issues/7007

devices. Fixed wrong input/output labels

---

pages/history.tsx

https://github.com/NethServer/dev/issues/7021

history: added open button for report redirect

---

pages/settings.tsx

https://github.com/NethServer/dev/issues/7014

settings. Hide mobile app tab inside settings

---

components/queueManager/NotManaged/NotManagedCalls.tsx
components/queueManager/NotManaged/NotManagedCallsFilter.tsx
components/queues/CallsView.tsx
components/queues/CallsViewFilter.tsx

https://github.com/NethServer/dev/issues/7028

No queue selection as standard inside queues filter

---

components/layout/Layout.tsx
components/queueManager/Realtime/RealTimeManagement.tsx
models/queueManager.ts
models/queues.ts
package-lock.json
package.json

https://github.com/NethServer/dev/issues/7031

Fixed missing operator update status

---

components/history/ShowHistoryDrawerContent.tsx
lib/operators.ts
public/locales/en/translation.json
public/locales/it/translation.json

- Fixed insertion of operator in case of speedDial operator username
- Added missing translations

Avoid speedDials operators to be set as favourite

---

components/layout/Layout.tsx
lib/speedDial.ts
package-lock.json
package.json

**Reference** : https://github.com/NethServer/dev/issues/7060

fix(speeddial): adjust import with favourites type

---

components/layout/Layout.tsx
package-lock.json
package.json

**Reference** : https://github.com/NethServer/dev/issues/7118
*See also* : 
- https://github.com/nethesis/nethcti-server/pull/324
- https://github.com/nethesis/ns8-nethvoice/pull/348
- https://github.com/nethesis/phone-island/pull/66

feat: added update default_device phone-island listener

---

package-lock.json
package.json
public/locales/en/translation.json
public/locales/it/translation.json

**Reference** : https://github.com/NethServer/dev/issues/7118

feat: new phone-island version

---

package-lock.json
package.json
public/locales/en/translation.json
public/locales/it/translation.json

Reference: https://github.com/NethServer/dev/issues/7118

chore(locales): update locales

---

components/layout/TopBar.tsx

**Reference** : https://github.com/NethServer/dev/issues/7118

fix: wrong device selection inside topBar

---

components/devices/DeviceSectionOperatorSearch.tsx
components/layout/Layout.tsx

**Reference** : https://github.com/NethServer/dev/issues/7152

fix: missing information on custom number inside physical buttons

---

components/common/ActionCall.tsx
lib/operators.ts
package-lock.json
package.json
public/locales/en/translation.json
public/locales/it/translation.json

**reference** : https://github.com/NethServer/dev/issues/7262

fix: added missing pickup call action

---

components/layout/Layout.tsx
package-lock.json
package.json

**Reference** : https://github.com/NethServer/dev/issues/7267

chore(dep): update phone-island

---

package-lock.json
package.json

Reference:
- https://github.com/NethServer/dev/issues/7135

chore(dep): update phone-island to v0.13.0

---

components/common/CopyComponent.tsx
components/layout/GlobalSearch.tsx
components/layout/Layout.tsx
components/operators/Filter.tsx
components/phonebook/ContactSummary.tsx
lib/operators.ts
lib/utils.ts
models/operators.ts
models/user.ts
package-lock.json
package.json
pages/operators.tsx
public/locales/en/translation.json
public/locales/it/translation.json
store/index.ts

- Show only groups and operators according to user permissions
- Implement logic for the new `all_groups` permission
Ref:
- https://github.com/NethServer/dev/issues/7277

fix: show groups and operators according to permissions

---

components/common/UserRightSideMenu/SpeedDialContent.tsx
components/history/calls/Calls.tsx
pages/history.tsx

[NethServer/dev#7136](https://github.com/NethServer/dev/issues/7136)

fix: voicemails fixes

---

components/devices/DownloadDesktopLinkContent.tsx
components/settings/Devices.tsx
lib/devices.tsx

**Reference**:
- https://github.com/NethServer/dev/issues/7341

fix: edited file for nethlink download

---

components/settings/MobileApp.tsx
entrypoint.sh
lib/utils.ts

Reference:
- https://github.com/NethServer/dev/issues/7423

fix(qrcode): set app CloudID

---

lib/utils.ts
package-lock.json
package.json

**Reference**: 
- https://github.com/NethServer/dev/issues/7403

fix: transfer protocol if NethLink is online

---

Dockerfile

https://github.com/NethServer/dev/issues/7517

feat(dockerfile): install curl for health checks

---

components/customerCards/CustomerCards.tsx
components/history/LastCallsDrawerTable.tsx
components/layout/Layout.tsx
components/phonebook/ContactSummary.tsx
config/router/RouterGuard.tsx
lib/history.ts
pages/customercards.tsx

Reference:
- https://github.com/NethServer/dev/issues/7531

fix: update customer card routing
